config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :tasks
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create 
    @category = Category.create!(category_params)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update!(category_params)
    redirect_to category_path(@category)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>  
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, placeholder: "Please put category name" %>
  <%= f.submit %>
<% end %>

app/views/categories/create.html.erb
<p><%= @category.name %></p>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<% @categories.each do |category|  %>
  <%= category.name %>
  <%= link_to "Show", category_path(category)   %>
<% end %>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<%= @category.name %>
<%= link_to "Edit", edit_category_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>